-- Clinic Monitoring System schema for Oracle
-- Run each statement individually in APEX SQL Workshop

-- ===== CREATE TABLES =====

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(10) NOT NULL
);

-- After running the above, run this:

CREATE TABLE appointments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    staff_id NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time VARCHAR2(10) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
    CONSTRAINT fk_appointments_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_appointments_staff FOREIGN KEY (staff_id) REFERENCES users(id)
);

-- ===== INSERT SAMPLE DATA =====
-- After creating tables, run the inserts below one at a time:

INSERT INTO users (name, email, password, role) 
VALUES ('Clinic Admin', 'admin@example.com', 'scrypt:32768:8:1$mUX86qGtZqu0zLHf$513a891eee6170b9bf445e97eda1e79b2a825ca0638e04a7bdc0663ff1e6387591d309a97b934769bbab00fda7d69187a1fbf784d7b2ab4674f530d0781b9b8e', 'admin');

INSERT INTO users (name, email, password, role) 
VALUES ('Front Desk Staff', 'staff@example.com', 'scrypt:32768:8:1$mUX86qGtZqu0zLHf$513a891eee6170b9bf445e97eda1e79b2a825ca0638e04a7bdc0663ff1e6387591d309a97b934769bbab00fda7d69187a1fbf784d7b2ab4674f530d0781b9b8e', 'staff');

INSERT INTO users (name, email, password, role) 
VALUES ('Patient User', 'user@example.com', 'scrypt:32768:8:1$mUX86qGtZqu0zLHf$513a891eee6170b9bf445e97eda1e79b2a825ca0638e04a7bdc0663ff1e6387591d309a97b934769bbab00fda7d69187a1fbf784d7b2ab4674f530d0781b9b8e', 'user');

INSERT INTO appointments (user_id, staff_id, appointment_date, appointment_time, status) 
VALUES (
    (SELECT id FROM users WHERE email = 'user@example.com'),
    (SELECT id FROM users WHERE email = 'staff@example.com'),
    TO_DATE('2026-05-05', 'YYYY-MM-DD'),
    '10:30',
    'Confirmed'
);

INSERT INTO appointments (user_id, staff_id, appointment_date, appointment_time, status) 
VALUES (
    (SELECT id FROM users WHERE email = 'user@example.com'),
    (SELECT id FROM users WHERE email = 'staff@example.com'),
    TO_DATE('2026-05-12', 'YYYY-MM-DD'),
    '14:00',
    'Pending'
);

COMMIT;
